version: '3'

services:
  job_title_normalizer:
    image: job_title_normalizer:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./data:/data
      - ./notebooks:/notebooks
    entrypoint: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--NotebookApp.token=", "--notebook-dir=/notebooks", "--allow-root", "--no-browser"]
